"""ship del

Revision ID: 4d41b4b3c6a2
Revises: 9f1b6e69363e
Create Date: 2024-10-18 13:49:23.262783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d41b4b3c6a2'
down_revision = '9f1b6e69363e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('shipping')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
