"""ord

Revision ID: 67e6660ab8c3
Revises: 6b59482425c8
Create Date: 2024-11-03 13:45:06.204134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e6660ab8c3'
down_revision = '6b59482425c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=256), nullable=False))

    # ### end Alembic commands ###
